version: '2'
services:
    myapp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/myApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=myApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
